CREATE DATABASE Team8_DuAn1_2408
USE Team8_DuAn1_2408

GO
-- ThietKe
CREATE TABLE ThietKe(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL,
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
-- DoiTuongSuDung
CREATE TABLE DoiTuongSuDung(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL, 
KichThuoc DECIMAL(20,2) DEFAULT NULL,
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
-- NSX
CREATE TABLE NSX(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL, 
QuocGia NVARCHAR(50) DEFAULT NULL, 
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
-- MauSac
CREATE TABLE MauSac(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL ,
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
-- SanPham
CREATE TABLE SanPham(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL ,
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
-- Lop
CREATE TABLE Lop(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
SoLuong int DEFAULT NULL,
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
)

GO
--ChiTietSP
CREATE TABLE ChiTietSP(
MaQR BIGINT PRIMARY KEY ,
NgaySanXuat Date DEFAULT NULL,
HanSuDung Date DEFAULT NULL,
Gia DECIMAL(20,0) DEFAULT NULL,
MoTa NVARCHAR(50) DEFAULT NULL,
TrongLuong DECIMAL(20,0) DEFAULT NULL,
SoLuong int DEFAULT NULL,
TrangThai INT DEFAULT 0 ,
IdTK BIGINT , 
IdDTSD BIGINT , 
IdNSX BIGINT , 
IdMS BIGINT , 
IdSP BIGINT , 
IdLop BIGINT , 
)

GO
-- ChucVu
CREATE TABLE ChucVu(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL 
)
insert into ChucVu values
('ma01',N'quản lý'),
('ma02',N'nhân viên')
select *
from
ChucVu

GO
-- Thu2
CREATE TABLE Thu2(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)

GO
-- Thu3
CREATE TABLE Thu3(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
-- T4
CREATE TABLE Thu4(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
-- T5
CREATE TABLE Thu5(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
-- T6
CREATE TABLE Thu6(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
-- T7
CREATE TABLE Thu7(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
-- CN
CREATE TABLE ChuNhat(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
Ca NVARCHAR(50) DEFAULT NULL 
)
GO
--NhanVien
CREATE TABLE NhanVien(
MaQR BIGINT PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL, 
GioiTinh NVARCHAR(50) DEFAULT NULL,
Email NVARCHAR(50) DEFAULT NULL,
QueQuan NVARCHAR(50) DEFAULT NULL,
NgaySinh Date DEFAULT NULL,
Sdt VARCHAR(15) DEFAULT NULL,
MatKhau NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 0 ,
IdChucVu BIGINT , 
)
insert into NhanVien values
(12072005,'ma01','minh',N'true',N'minh@gmail.com',N'HN','2003-03-09','0388598451','1',DEFAULT,1),
(12072006,'ma02','dương',N'true',N'd@gmail.com',N'HN','2002-12-12','0123467890','1',DEFAULT,1)
select *
from
NhanVien

GO
-- DanhSachLamViec
CREATE TABLE DanhSachLamViec(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
NgayTao Date DEFAULT NULL,
NgaySua Date DEFAULT NULL,
IdT2 BIGINT ,
IdT3 BIGINT ,
IdT4 BIGINT ,
IdT5 BIGINT ,
IdT6 BIGINT ,
IdT7 BIGINT ,
IdCN BIGINT ,
MaQRNhanVien BIGINT
)
GO
-- CheckIn
CREATE TABLE CheckIn(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
NgayTao Date DEFAULT NULL,
GioVao VARCHAR(50) DEFAULT NULL,
PhutVao VARCHAR(50) DEFAULT NULL,
PhutCoDinh VARCHAR(50) DEFAULT 0,
BaoCao NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 0 ,
MaQRNhanVien BIGINT
)
GO
-- CheckOut
CREATE TABLE CheckOut(
Id BIGINT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE, 
NgayTao Date DEFAULT NULL,
GioRa VARCHAR(50) DEFAULT NULL,
BaoCao NVARCHAR(50) DEFAULT NULL,
MaQRNhanVien BIGINT
)
GO

--KhachHang
CREATE TABLE KhachHang(
MaQR BIGINT PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL, 
GioiTinh NVARCHAR(50) DEFAULT NULL,
Email NVARCHAR(50) DEFAULT NULL,
QueQuan NVARCHAR(50) DEFAULT NULL,
NgaySinh Date DEFAULT NULL,
Sdt VARCHAR(15) DEFAULT NULL,
TrangThai INT DEFAULT 0 ,
)
insert into KhachHang values
(87647384,'ma01','minh',N'true',N'minh@gmail.com',N'HN','2003-03-09','0123467890',DEFAULT),
(87647385,'ma02','dương',N'true',N'd@gmail.com',N'HN','2002-12-12','0123467890',DEFAULT)
GO
--PhieuGiamGia
CREATE TABLE PhieuGiamGia(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE, 
Ten NVARCHAR(50) DEFAULT NULL, 
NgayBD Date DEFAULT NULL,
NgayKT Date DEFAULT NULL,
HinhThucGiamGia VARCHAR(50) DEFAULT NULL,
GiaTriGiam DECIMAL(20,0) DEFAULT NULL,
TrangThai INT DEFAULT 0 , 
)
GO
--HoaDon
CREATE TABLE HoaDon(
Id BIGINT IDENTITY(1,1) PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE,
NgayTao Date DEFAULT NULL,
NgayThanhToan Date DEFAULT NULL,
NgayHuy Date DEFAULT NULL,
MoTa NVARCHAR(50) DEFAULT NULL,
TienKhachDua DECIMAL(20, 0) DEFAULT 0,
TienThua DECIMAL(20, 0) DEFAULT 0,
TrangThai INT DEFAULT 0 ,
MaQRKhachHang BIGINT ,
MaQRNhanVien BIGINT,
IdPhieuGiamGia BIGINT ,
)
GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
IdHoaDon BIGINT ,
MaQRCTSP BIGINT ,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
TongTien DECIMAL(20,0), 
TrangThai INT DEFAULT 0 ,
CONSTRAINT PK_HoaDonChiTiet PRIMARY KEY (IdHoaDon,MaQRCTSP),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id),
CONSTRAINT FK2 FOREIGN KEY(MaQRCTSP) REFERENCES ChiTietSP(MaQR),
)

GO
-- ChiTietSP - ThietKe
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdTK) REFERENCES ThietKe(Id)
-- ChiTietSP - DoiTuongSuDung
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdDTSD) REFERENCES DoiTuongSuDung(Id)
-- ChiTietSP - NSX
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdNSX) REFERENCES NSX(Id)
-- ChiTietSP - MauSac
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdMS) REFERENCES MauSac(Id)
-- ChiTietSP - SanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSP) REFERENCES SanPham(Id)
-- ChiTietSP - Lop
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdLop) REFERENCES Lop(Id)
--NhanVien - ChucVu
ALTER TABLE NhanVien ADD FOREIGN KEY(IdChucVu) REFERENCES ChucVu(Id)
--HoaDon - NhanVien
ALTER TABLE HoaDon ADD FOREIGN KEY(MaQRNhanVien) REFERENCES NhanVien(MaQR)
--HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY(MaQRKhachHang) REFERENCES KhachHang(MaQR)
-- HoaDon - PhieuGiamGia
ALTER TABLE HoaDon ADD FOREIGN KEY(IdPhieuGiamGia) REFERENCES PhieuGiamGia(Id)
-- DanhSachLamViec - T2
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT2) REFERENCES Thu2(Id)
-- DanhSachLamViec - T3
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT3) REFERENCES Thu3(Id)
-- DanhSachLamViec - T4
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT4) REFERENCES Thu4(Id)
-- DanhSachLamViec - T5
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT5) REFERENCES Thu5(Id)
-- DanhSachLamViec - T6
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT6) REFERENCES Thu6(Id)
-- DanhSachLamViec - T7
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdT7) REFERENCES Thu7(Id)
-- DanhSachLamViec - CN
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(IdCN) REFERENCES ChuNhat(Id)
-- DanhSachLamViec - NhanVien
ALTER TABLE DanhSachLamViec ADD FOREIGN KEY(MaQRNhanVien) REFERENCES NhanVien(MaQR)
-- CheckIn - NhanVien
ALTER TABLE CheckIn ADD FOREIGN KEY(MaQRNhanVien) REFERENCES NhanVien(MaQR)
-- CheckOut - NhanVien
ALTER TABLE CheckOut ADD FOREIGN KEY(MaQRNhanVien) REFERENCES NhanVien(MaQR)
